<div class="row">
  <div class="col-sm-12 text-center">
      <div class="box">
              <hr>
              <h2 class="intro-text ">Seznam uživatelů</h2>
              <hr>
          <div>
              <table class="table table-hover">
                  <thead>
                  <tr>
                      <th>Uživatelské jméno</th>
                      <th>Jméno</th>
                      <th>Email</th>
                      <th>Role</th>
                      <th></th>
                  </tr>
                  </thead>
                  <tbody>
                  <?php
                  foreach ($_SESSION['users'] as $user) :?>
                      <tr>
                          <td><?= $user['login'] ?></td>
                          <td><?= $user['name'] ?></td>
                          <td><?= $user['email'] ?></td>
                          <form method="POST">
                          <td>
                              <div class="form-group">
                                  <select class="form-control" name="select" id="role"><?php
                                  $the_key = $user['rights_id_rights']; // or whatever you want
                                  foreach(array(
                                      1 => 'Administrátor',
                                      2 => 'Autor',
                                      3 => 'Recenzent',
                                  ) as $key => $val){
                                      ?><option value="<?php echo $key; ?>"<?php
                                          if($key==$the_key)echo ' selected="selected"';
                                      ?>><?php echo $val; ?></option><?php
                                  }
                              ?></select>
                              </div>
                          </td>
                          <td>
                              <?php if($_SESSION["user"]["login"] != $user['login']) :?>
                                  <button type="submit" name="accept" class="btn btn-info">Změnit</button>
                                  <input type="hidden" name="id" value="<?php echo $user['id_users']; ?>">
                              <?php endif?>
                          </td>
                          </form>
                      </tr>
                  <?php endforeach; ?>
                  </tbody>
              </table>
          </div>
      </div>
  </div>
</div>