<div class="text-center">
    <div class="box center">
            <hr>
        <?php if($_SESSION['post']['published'] == 1) :?>
            <h2 class="intro-text">Hodnocení příspěvku: <span class="published">Publikováno</span></h2>
        <?php endif; ?>
        <?php if($_SESSION['post']['published'] == 2) :?>
            <h2 class="intro-text">Hodnocení příspěvku: <span class="denyed">Zamítnuto</span></h2>
        <?php endif; ?>
            <hr>

        <div class="left">
            <h2>Název: <?= $_SESSION['post']['name']?><h2>
                    <h4>Autoři: <?= $_SESSION['post']['author']?><h3>
                            <h4>Abstrakt:</h4>
                            <p class="abstract box"><?= $_SESSION['post']['abstract']?></p>

        </div>
        <div><a class="btn btn-info" href="uploads/<?= $_SESSION['post']['filename']?>" target="_blank" download>Stáhnout <?= $_SESSION['post']['filename']?></a></div>
        <div class="row">
        <?php for($i = 0; $i < 3; $i++) : ?>
            <div class="col-sm-4 text-center">
                <div class="row"><h4>Recenzent: <?= $_SESSION['raters'][$i]['name']?></h4></div>
                <div class="row">
                    <div class="row ">
                        <div class="col-sm-1 text-center "> </div>
                        <div class="col-sm-2 text-center heading">Org.</div>
                        <div class="col-sm-2 text-center heading">Téma</div>
                        <div class="col-sm-2 text-center heading">Jazyk</div>
                        <div class="col-sm-2 text-center heading">Celkem</div>
                        <div class="col-sm-1 text-center heading">.</div>
                    </div><div class="row ">
                        <div class="col-sm-1 text-center"></div>
                        <div class="col-sm-2 text-center cell"><?= $_SESSION['ratings'][$i]['originality']?></div>
                        <div class="col-sm-2 text-center cell"><?= $_SESSION['ratings'][$i]['topic']?></div>
                        <div class="col-sm-2 text-center cell"><?= $_SESSION['ratings'][$i]['language_level']?></div>
                        <div class="col-sm-2 text-center cell"><?= $_SESSION['ratings'][$i]['avg']?></div>
                        <div class="col-sm-1 text-center"></div>
                    </div>
                </div>
                <div class="row">
                    <h4>Komentář:</h4>
                    <p class="abstract box"><?= $_SESSION['ratings'][$i]['comment']?></p>
                </div>



        </div>
        <?php endfor; ?>
        </div>
            <div>
                <a class="btn btn-default" href="info_logged/posts">Zpět</a>
            </div>
        </form>
    </div>
</div>