<div class="text-center">
    <div class="box center">
            <hr>
            <h2 class="intro-text ">Upravit příspěvek</h2>
            <hr>

        <form role="form-horizontal" class="cont-center" method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label class="control-label" for="name">Název:</label>
                <input type="text" name="name" class="form-control" id="name" value="<?= $_SESSION['post']['name']?>" required>
            </div>
            <div class="form-group">
                <label class="control-label" for="authors">Autoři</label>
                <input type="text" name="authors" class="form-control" id="authors" value="<?= $_SESSION['post']['author']?>" required>
            </div>
            <div class="form-group">
                <label class="control-label" for="abstract">Abstrakt</label>
                <textarea name="abstract" class="form-control" rows="5" id="abstract" required><?= $_SESSION['post']['abstract']?></textarea>

            </div>
            <div class="form-group">
                <label class="control-label" for="file">Soubor</label>
                <input type="file" name="fileToUpload"  id="file" accept=".pdf" required>
                <p class="inputInfo">Nahrávejte pouze PDF soubory!</p>
            </div>
            <div class="form-group">
                <button type="submit" name="accept" class="btn btn-primary">Uložit</button>
                <a class="btn btn-default" href="users">Zpět</a>
            </div>
        </form>
    </div>
</div>