<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#info-navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <a class="navbar-brand" href="info/introduction">Informace</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="info-navbar">
            <ul class="nav navbar-nav navbar-info">
                <li>
                    <a href="info/introduction">O konferenci</a>
                </li>
                <li>
                    <a href="info/venue">Místo konání</a>
                </li>
                <li>
                    <a href="info/leaders">Organizátoři</a>
                </li>
                <li>
                    <a href="info/instructions">Pokyny pro autory</a>
                </li>
                <li>
                    <a href="info/sponsors">Sponzoři</a>
                </li>
                <li>
                    <a href="info/dates">Termíny</a>
                </li>
                <li>
                    <a href="info/published">Publikace</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<?php  $this->controller->getView(); // vložení aktuálního pohledu do šablony ?>

