<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#info-navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <a class="navbar-brand" href="info/introduction">Pro uživatele</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="info-navbar">
            <ul class="nav navbar-nav navbar-info navbar-left">
                <?php if($_SESSION["user"]["rights_id_rights"] == 2 || $_SESSION["user"]["rights_id_rights"] == 1) :?>
                <li>
                    <a href="info_logged/posts">Příspěvky</a>
                </li>
                <?php endif; if($_SESSION["user"]["rights_id_rights"] == 3 || $_SESSION["user"]["rights_id_rights"] == 1) :?>
                <li>
                    <a href="info_logged/ratings">Hodnocení</a>
                </li>
                <?php endif; if($_SESSION["user"]["rights_id_rights"] == 1) :?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Administrace <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="info_logged/admposts">Příspěvky</a></li>
                        <li><a href="info_logged/admusers">Uživatelé</a></li>
                    </ul>
                </li>
                <?php endif; ?>
            </ul>
             <ul class="nav navbar-nav navbar-info navbar-right">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><?php print($_SESSION["user"]["login"]); ?> <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                      <li><a href="login">Odhlásit</a></li>
                  </ul>
              </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<?php  $this->controller->getView(); // vložení aktuálního pohledu do šablony ?>

