<div class="container text-center">
    <div class="box center">
            <hr>
            <h2 class="intro-text ">Přihlásit</h2>
            <hr>

        <?php if($message != null) :?>
            <div class="alert alert-danger">
                <?php  echo $message; ?>
            </div>
        <?php endif; ?>
        <form role="form-horizontal" class="cont-center" method="POST">
            <div class="form-group">
                <label class="control-label" for="login">Uživatelské jméno:</label>
                <input type="text" name="login" class="form-control" id="login" placeholder="Uživatelské jméno" required>
            </div>
            <div class="form-group">
                <label class="control-label" for="pwd">Heslo:</label>
                <input type="password" name="password" class="form-control" id="pwd" placeholder="Heslo" required>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox">Zůstat přihlášen</label>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" name="accept" class="btn btn-primary">Přihlásit</button>
                <a class="btn btn-default" href="users">Zpět</a>
            </div>
        </form>
    </div>
</div>