<div class="row">
  <div class="col-sm-12 text-center">
      <div class="box center">
              <hr>
              <h2 class="intro-text ">Příspěvky</h2>
              <hr>
          <div>
              <table class="table table-hover">
                  <thead>
                  <tr>
                      <th>Název</th>
                      <th>Autoři</th>
                      <th></th>
                  </tr>
                  </thead>
                  <tbody>
                  <?php
                  if( $_SESSION['posts'] != null):
                  foreach ( $_SESSION['posts'] as $post) :?>
                      <tr>
                          <td><?= $post['name'] ?></td>
                          <td><?= $post['author'] ?></td>
                          <td>
                              <form method="POST" class="pull-right">
                                  <?php if( $_SESSION['user']['id_users'] == $post['users_id_users'] && $post['published'] !== 0 && $post['published'] == NULL): ?>
                                  <button type="submit" name="edit" class="btn btn-info"><span class="glyphicon glyphicon-pencil"></span></button>
                                  <?php endif; ?>
                                  <?php if($post['published'] === 0): ?>
                                      <a class="btn btn-warning"><span class="glyphicon glyphicon-lock"></span> Hodocení</a>
                                  <?php endif; ?>
                                  <?php if( $post['published'] == 1): ?>
                                      <button type="submit" name="display" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Zobrazit</button>
                                  <?php endif; ?>
                                  <?php if( $post['published'] == 2): ?>
                                      <button type="submit" name="display" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Zobrazit</button>
                                  <?php endif; ?>
                                  <button type="submit" name="delete" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></button>
                                  <input type="hidden" name="id" value="<?php echo $post['id_posts']; ?>">
                              </form>
                          </td>
                      </tr>
                  <?php
                  endforeach;
                  endif; ?>
                  </tbody>
              </table>
          </div>
          <?php if( $_SESSION['posts'] == null):?>
          <p class="alert">Žádné články nejsou k dispozici!</p>
          <?php endif; ?>
          <a class="btn btn-primary" href="addpost">Přidat příspěvek</a></br>
      </div>
  </div>
</div>