<div class="row">
    <div class="box">
        <div class="col-lg-12 text-center">
            <hr>
            <h2 class="error-text">Nutné přihlášení</h2>
            <hr>
            <p>Tato sekce je přístupná pouze přihlášeným uživatelům. Prosíme přihlašte se. </p>
            <a class="btn btn-primary btn-lg" href="login">Přihlásit</a></br>
            <a class="btn btn-default btn-md" href="register">Registrovat</a>
            </div>
    </div>
</div>